### ISSUE TITLE
Map out routes, URLs and simplify + Webflow

### ISSUE THREAD

**Issue by Gerdusvdl** [CUSP-Urban-Science-and-Policy/Citizen-Voice#79]
Take a look at all our URLs and routes and map them out, so that we have a clear overview and that we can simplify it.

**Comment by Esthetech** [comment]
Edit: I added the '+ webflow' to this ticket.
It's closely related and can be represented in one flowchart.

**Comment by Esthetech** [comment]
See: https://miro.com/app/board/uXjVOuGh6gI=/?moveToWidget=3458764540659106925&cot=14
