### ISSUE TITLE
Start on homepage

### ISSUE THREAD

**Issue by Esthetech** [CUSP-Urban-Science-and-Policy/Citizen-Voice#90]
Collect all data that need to go on the homepage and make a quick representation of it (without too much styling)

**Comment by manuGil** [comment]
@jgves  Maybe you will also want to provide some text for this page in preparation for the video. We can reuse something you have or something generic from the project proposal/documentation.

**Comment by manuGil** [comment]
The citizen voice app will be integrated into another website. A home page is not necessary.
